env:
  browser: true
  es6: true
  mocha: true
extends: airbnb-base, 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
